os: osx
osx_image: xcode12
language: swift
cache:
  directories:
  - .autoconf
  - $HOME/.m2
script: xcodebuild build test -workspace CleanCrypto.xcworkspace -scheme "CleanCrypto" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=14.0,name=iPhone 11" PLATFORM_NAME=iphonesimulator ONLY_ACTIVE_ARCH=YES CODE_SIGNING_REQUIRED=NO
