//
//  BitcoinModels.swift
//  CleanStore
//
//  Created by João Pedro Giarrante on 27/09/20.
//  Copyright (c) 2020 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CryptoModels {
    // MARK: Use cases
    
    enum FetchCrypto {
        struct Request {
            var ticket: String
            var currency: String
        }
        struct Response: Codable {
            var time, assetIdBase, assetIdQuote: String?
            var rate: Double?
            enum CodingKeys: String, CodingKey {
                case time
                case assetIdBase
                case assetIdQuote
                case rate
            }
        }
        struct ViewModel {
            struct DisplayedCrypto {
                var price: String
                var ticket: String
            }
            var displayedCrypto: DisplayedCrypto
        }
    }
}
