//
//  CryptoPresenter.swift
//  CleanStore
//
//  Created by João Pedro Giarrante on 27/09/20.
//  Copyright (c) 2020 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CryptoPresentationLogic
{
    func presentFetchedCrypto(response: CryptoModels.FetchCrypto.Response)
}

class CryptoPresenter: CryptoPresentationLogic
{
    weak var viewController: CryptoDisplayLogic?
    
    // MARK: Do something
    
    func presentFetchedCrypto(response: CryptoModels.FetchCrypto.Response)
    {
        var displayedCrypto: CryptoModels.FetchCrypto.ViewModel.DisplayedCrypto
        
        var formattedPrice = " Não Encontrado "
        
        // Using Extension
        if let code = response.crypto.assetIDQuote, let value = response.crypto.rate {
            formattedPrice = String.formatValueForCurrencyCode(value: value, myCode: code) ?? " Não Encontrado "
        }
        
        // Creating ViewModel
        displayedCrypto = CryptoModels.FetchCrypto.ViewModel.DisplayedCrypto(price: formattedPrice, ticket: response.crypto.assetIDBase ?? " ? ")
        
        // Displaying
        let viewModel = CryptoModels.FetchCrypto.ViewModel(displayedCrypto: displayedCrypto)
        viewController?.displayFetchedCrypto(viewModel: viewModel)
    }
}
