//
//  CryptoDetailInteractor.swift
//  CleanCrypto
//
//  Created by João Pedro Giarrante on 28/09/20.
//  Copyright (c) 2020 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CryptoDetailBusinessLogic {
    func getCryptoData(request: CryptoDetailModels.SelectedCrypto.Request)
}

protocol CryptoDetailDataStore {
    var crypto: CryptoModels.FetchCrypto.Response! { get set }
}

class CryptoDetailInteractor: CryptoDetailBusinessLogic, CryptoDetailDataStore {
    var presenter: CryptoDetailPresentationLogic?
    var worker: CryptoDetailWorker?
    var crypto: CryptoModels.FetchCrypto.Response!
    
    // MARK: Get CryptoData
    
    func getCryptoData(request: CryptoDetailModels.SelectedCrypto.Request) {
        if let response = self.crypto {
            presenter?.presentCryptoData(response: response)
        }
        
        
    }
}
