//
//  CryptoDetailModels.swift
//  CleanCrypto
//
//  Created by João Pedro Giarrante on 28/09/20.
//  Copyright (c) 2020 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CryptoDetailModels {
  // MARK: Use cases
  
  enum SelectedCrypto {
    struct Request { }
    
    struct Response { }
    
    struct ViewModel {
        struct DisplayedCrypto {
            var price: String
            var ticket: String
            var variacao24H: String
            var variacaoMes: String
            var variacaoAno: String
        }
        var displayedCrypto: DisplayedCrypto
    }
  }
}
