//
//  CryptoDetailPresenter.swift
//  CleanCrypto
//
//  Created by João Pedro Giarrante on 28/09/20.
//  Copyright (c) 2020 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CryptoDetailPresentationLogic {
  func presentCryptoData(response: CryptoDetail.CryptoData.Response)
}

class CryptoDetailPresenter: CryptoDetailPresentationLogic {
  weak var viewController: CryptoDetailDisplayLogic?
  
  // MARK: Do something
  
  func presentCryptoData(response: CryptoDetail.CryptoData.Response) {
    var displayedCrypto: CryptoDetail.CryptoData.ViewModel.DisplayedCrypto
    
    var formattedPrice = " Não Encontrado "
    
    // Using Extension
    if let code = response.crypto.assetIDQuote, let value = response.crypto.rate {
        formattedPrice = String.formatValueForCurrencyCode(value: value, myCode: code) ?? " Não Encontrado "
    }
    
    // Creating ViewModel
    displayedCrypto = CryptoDetail.CryptoData.ViewModel.DisplayedCrypto(price: formattedPrice, ticket: response.crypto.assetIDBase ?? " ? ", variacao24H: "+ 2.73%", variacaoMes: "- 5.41%", variacaoAno: "+ 29.68%")
    
    // Displaying
    let viewModel = CryptoDetail.CryptoData.ViewModel(displayedCrypto: displayedCrypto)
    viewController?.displayCryptoData(viewModel: viewModel)
  }
}
